package com.example.hospitalmanagement.dto;

import lombok.Data;

@Data
public class AppointmentDTO {

    // ============================
    // PRIMARY ID (IMPORTANT FIX)
    // ============================
    private Long id;   // <<< REQUIRED FOR VIEW/EDIT URLS

    // ============================
    // RELATION IDS
    // ============================
    private Long patientId;
    private Long doctorId;
    private Long departmentId;

    // ============================
    // RELATION NAMES (Frontend display)
    // ============================
    private String patientName;
    private String doctorName;
    private String departmentName;

    // ============================
    // CORE APPOINTMENT FIELDS
    // ============================
    private String appointmentDate;      // LocalDateTime as string
    private String status;               // Scheduled / Completed / Cancelled / etc.
    private String serialNo;             // Auto-generated by backend
    private String problem;
    private String chiefComplaint;

    // ============================
    // WORKFLOW
    // ============================
    private String appointmentType;          
    private Integer plannedDurationMinutes;
    private Boolean isFollowUp;
    private String roomNumber;
    private String remarks;
    private String cancellationReason;

    // ============================
    // BILLING
    // ============================
    private Double fee;
    private String paymentStatus;            

    // ============================
    // CODING
    // ============================
    private String icd10Code;
    private String cptCode;

    // ============================
    // AUDIT FIELDS
    // ============================
    private String checkInTime;              
    private String checkOutTime;             
    private String lastModifiedBy;
}
