spring.application.name=hospitalmanagement

# H2 in-memory
spring.datasource.url=jdbc:h2:mem:hospitaldb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# ensure data.sql runs after Hibernate creates schema
spring.jpa.defer-datasource-initialization=true

# H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# simplify security for local dev (we also configure SecurityConfig)
spring.security.user.name=admin
spring.security.user.password=admin123
